name: Backend Pull Request Check

on:
  pull_request:
    branches: [ main ]
    paths:
        - 'backend/**'    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  release:
    types: [published]

jobs:
  checking-pr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/

    - name: Cd to the directory to test
      working-directory: ./backend
      run: |
          yarn install
          yarn pr-check